config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/', to: "home#index"
  get '/:username', to: 'dashboard#index'
  get '/:username/?tab=repositories', to: 'dashboard#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hub_user.rb
class HubUser

  attr_reader :id,
              :name,
              :image,
              :company,
              :location,
              :bio,
              :public_repos,
              :public_gists,
              :followers,
              :following

  def initialize(data={})
    @id = data[:id]
    @name = data[:name]
    @image = data[:avatar_url]
    @company = data[:company]
    @location = data[:location]
    @bio = data[:bio]
    @public_repos = data[:public_repos]
    @public_gists = data[:public_gists]
    @followers = data[:followers]
    @following = data[:following]
  end

end

app/models/user.rb
class User < ApplicationRecord


  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid       = auth_info.uid
      new_user.username  = auth_info.info.nickname
      new_user.token     = auth_info.credentials.token
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

    if params[:username]
      handle = params[:username]
    else
      handle = current_user.username
    end
    @displayed_user = ApiData.return_repo_data(current_user.token, handle )
    @params = params
    @root = "http://localhost:3000/"


  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# skip_before_action :verify_authenticity_token, only: :create

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to "/#{user.username}"
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_followers.html.erb
<div class="box followers">
  <h3>Followers</h3>
      <div class"list_followers">
      <% @displayed_user.followers_all.each do |f|  %>
      <div class="box bottom-line">
        <%= image_tag f.image, size: "50x50"  %></br>
        <h3 class="text-color-blue"><%=f.username  %></br></h3>
      </div><!-- <div class="box bottom-line"> -->
      <%end %>
    </div><!-- <div class="list_followers"> -->
</div> <!-- <div class="box followers"> -->

app/views/dashboard/_following.html.erb
<div class="box following">
  <h3>Following</h3>
      <div class"list_following">
      <% @displayed_user.following_all.each do |f|  %>
      <div class="box bottom-line">
        <%= image_tag f.image, size: "50x50" %></br>
        <h3 class="text-color-blue"><%=f.username  %></br></h3>
      </div><!-- <div class="box bottom-line"> -->
      <%end %>
    </div><!-- <div class="list_followers"> -->
</div> <!-- <div class="box following"> -->

app/views/dashboard/_overview.html.erb
<div class="box overview">
  
</div><!-- <div class="box overview"> -->

app/views/dashboard/_repositories.html.erb
<div class="box repos">
<h3>Repositories</h3>
  <div class"list_repos">
  <% @displayed_user.repos.each do |repo|  %>

  <div class="box bottom-line">
    <h3 class="text-color-blue"><%=repo.name  %></br></h3>
    <p><%=repo.description  %></p></br>
    <p class="text-color-ltgrey"><%=" language   #{repo.language}   stars #{repo.stargazers_count}  forks #{repo.forks_count}"%></p>
  </div><!-- <div class="box"> -->

  <%end %>
  </div><!-- <div class="list_repos"> -->
</div><!-- <div class="box repos"> -->

app/views/dashboard/_starred.html.erb
<div class=" box starred-repos">
<h3>Stars</h3>
    <div class"list_starred">
    <% @displayed_user.starred.each do |star|  %>

    <div class="box bottom-line">
      <h3 class="text-color-blue"><%=star.full_name  %></br></h3>
      <p><%=star.description  %></p></br>
      <p class="text-color-ltgrey"><%="language #{star.language}   starred #{star.stargazers_count}   network #{star.network}"%></p>
    </div><!-- <div class="box bottom-line"> -->
    <%end %>
  </div><!-- <div class="list_starred"> -->

</div><!-- <div class="box starred-repos"> -->

app/views/dashboard/index.html.erb
<div class="box sidebar">
      <h2><%= image_tag @displayed_user.image, size: "200x200" %> </h2>
      <h2><%= @displayed_user.name %> </h2>
      <p class="bottom-line"><%= @displayed_user.bio  if @displayed_user.bio !=nil %> </p>
      <h3><%= @displayed_user.location if @displayed_user.location !=nil%> </h3>
      <h3 class="text-color-blue"><%= @displayed_user.email if @displayed_user.email !=nil%> </h3>
</div><!-- <div class="box sidebar"> -->

  <div class="box content">

      <div class="box content-inner-wrapper">
        <div class=" overview-tab center bottom-line">
          <h4>Overview</h4>
        </div><!-- <div class="overview-tab"> -->
        <div class="repo-tab center bottom-line">
          <h4> <%= link_to "Repositories #{@displayed_user.public_repos}", "#{@root}#{@displayed_user.name}/?tab=repositories" %> </h4>
        </div><!-- <div class="repo-tab"> -->
        <div class="stars-tab center bottom-line">
          <h4> <%= link_to "Stars #{@displayed_user.starred.count}", "#{@root}#{@displayed_user.name}/?tab=stars" %> </h4>
        </div><!-- <div class="stars-tab"> -->
        <div class="followers-tab center bottom-line">
          <h4> <%= link_to "Followers #{@displayed_user.followers}", "#{@root}#{@displayed_user.name}/?tab=followers" %> </h4>
        </div><!-- <div class="followers-tab"> -->
        <div class="following-tab center bottom-line">
          <h4> <%= link_to "Following #{@displayed_user.following}", "#{@root}#{@displayed_user.name}/?tab=following" %> </h4>
        </div><!-- <div class="following-tab"> -->
      </div><!-- <div class="content-inner-wrapper"> -->

      <div class="render-partials">
        <%= render 'dashboard/overview' if @params[:username]%>
        <%= render 'dashboard/repositories' if @params[:tab] == "repositories"%>
        <%= render 'dashboard/starred' if @params[:tab] == "stars"%>
        <%= render 'dashboard/followers' if @params[:tab] == "followers"%>
        <%= render 'dashboard/following' if @params[:tab] == "following"%>
      </div> <!-- <div class="render-partials"> -->

</div><!-- <div class="box content> -->

app/views/home/index.html.erb
<h1 class="center">Welcome to FakeHub: a GitHub clone</h1>

app/views/layouts/_footer.html.erb
  <p class="text-color-blue">Lauren Billington 2018</p>

app/views/layouts/_navbar.html.erb
<div class=" box nav-wrapper text-color-ltgrey bold">
  <p class="box git-links center">
    <%= link_to "Pull requests  ", "https://git.com/pulls"%>
    <%= link_to "Issues  ", "https://git.com/issues"%>
    <%= link_to "Marketplace  ", "https://git.com/Marketplace"%>
    <%= link_to "explore", "https://git.com/explore"%>
  </p>

    <% if current_user  %>
    <div class="box display-name">
      <p class="text-color-ltgrey"> Logged in as <%= current_user.username %></p>
    </div><!-- <div class="display-name"> -->
      <div class="box login-logout">
      <p><%= link_to "Logout", logout_path %></p>
    <% else %>
      <p class="text-color-blue"><%= link_to "Login with Github!", github_login_path %></p>
    <% end %>
  </div><!-- <div class="login-logout"> -->
</div><!-- <div class="nav-wrapper"> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakehub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="box site-wrapper">
      <div class="box header">
        <%= render 'layouts/navbar' %>
      </div><!-- <div class="box header"> -->

        <%= yield %>


    <div class="box footer center">
    <%= render 'layouts/footer' %>
    </div> <!-- <div class="box footer"> -->
  </div> <!-- <div class="site-wrapper"> -->

  </body>
</html>